<Project>
  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
    <CentralPackageTransitivePinningEnabled>true</CentralPackageTransitivePinningEnabled>
  </PropertyGroup>
  <ItemGroup>
    <GlobalPackageReference Include="Microsoft.CodeAnalysis.CSharp.CodeStyle" Version="5.9.0" />
    <GlobalPackageReference Include="Microsoft.Sbom.Targets" Version="4.1.5" />
    <GlobalPackageReference Include="Microsoft.NETFramework.ReferenceAssemblies" Version="1.0.3" Condition="'$(TargetFrameworkIdentifier)' == '.NETFramework'" />
  </ItemGroup>
  <ItemGroup>
    <PackageVersion Include="Aetos.CSharpPolyfills" Version="0.1.2" />
    <PackageVersion Include="JetBrains.Annotations" Version="2026.2.0" />
    <PackageVersion Include="Microsoft.CodeAnalysis.CSharp" Version="5.9.0" />
  </ItemGroup>
</Project>