using System;
using System.Collections.Immutable;
using System.Threading;
using System.Threading.Tasks;

using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Testing;
using Microsoft.CodeAnalysis.Testing;

using Aetos.EventSourceToolkit.Analyzers;

namespace Aetos.EventSourceToolkit.Tests.Analyzers;

[TestClass]
public sealed class EventSourceMethodSignatureAnalyzerTest
{
    private sealed class Test : CSharpAnalyzerTest<EventSourceMethodSignatureAnalyzer, DefaultVerifier>
    {
        /// <inheritdoc />
        protected override Task<(Compilation compilation, ImmutableArray<Diagnostic> generatorDiagnostics)> GetProjectCompilationAsync(
            Project project,
            IVerifier verifier,
            CancellationToken cancellationToken)
        {
            // この属性のためだけに EventSourceGenerator を追加しない。
            // Source Generator を参照しないので TestBehaviors.SkipGeneratedSourcesCheck も必要ない。
            // Source Generator 経由で追加するのでない場合、EmbeddedAttribute は出力されていないので付けない。
            var document = project.AddDocument(
                "Aetos.EventSourceToolkit.GeneratedEventSourceAttribute.g.cs",
                // lang=c#
                """
                // <auto-generated/>

                namespace Aetos.EventSourceToolkit
                {
                    [global::System.AttributeUsage(global::System.AttributeTargets.Class)]
                    [global::System.Diagnostics.Conditional("COMPILE_TIME_ONLY")]
                    internal sealed class GeneratedEventSourceAttribute : global::System.Attribute
                    {
                    }
                }
                """);

            return base.GetProjectCompilationAsync(document.Project, verifier, cancellationToken);
        }
    }

    [TestMethod]
    public async Task Foo()
    {
        // lang=c#
        const string Code =
            """
            using System.Diagnostics.Tracing;

            using Aetos.EventSourceToolkit;

            partial class MyEventSource : EventSource
            {
                public partial void Foo(E e, int i, byte[] b);
            }

            // Generator が動くようになるまで、エラーを避けるためのダミー実装
            partial class MyEventSource
            {
                public partial void Foo(E e, int i, byte[] b) { }
            }

            public enum E { A, B, C }
            """;

        var test = new Test
        {
            TestCode = Code
        };

        await test.RunAsync(this._testContext.CancellationToken).ConfigureAwait(false);
    }

    public EventSourceMethodSignatureAnalyzerTest(
        TestContext testContext)
    {
        ArgumentNullException.ThrowIfNull(testContext);

        this._testContext = testContext;
    }

    private readonly TestContext _testContext;

}
