// <auto-generated/>

using System;
using System.Collections.Generic;
using System.Diagnostics.Tracing;
using System.Text;

namespace EventConsumerProject.ExternalSource;

partial class ExternalEventListener
{
    private int _started = 0;

    public void Start()
    {
        if (Interlocked.Exchange(ref this._started, 1) != 0)
        {
            return;
        }

        foreach (var eventSource in EventSource.GetSources())
        {
            if (eventSource.Name != "ExternalEvents")
            {
                continue;
            }

            this.EnableEvents(eventSource);
        }
    }

    /// <inheritdoc />
    protected override void OnEventSourceCreated(EventSource eventSource)
    {
        if (Volatile.Read(ref this._started) == 0)
        {
            return;
        }

        if (eventSource.Name != "ExternalEvents")
        {
            return;
        }

        this.EnableEvents(eventSource);
    }

    private void EnableEvents(EventSource eventSource)
    {
        // インターフェイスモデルの場合に実行時にインターフェイス型にアクセスしないようにするため、EventKeywords はリテラルに置き換える
        // Level と Keywords は対応する実装クラス側に partial の実装があるものの和を取る。
        this.EnableEvents(eventSource, EventLevel.Informational, (EventKeywords)1);
    }

    /// <inheritdoc />
    protected override void OnEventWritten(EventWrittenEventArgs eventData)
    {
        if (eventData.EventSource.Name != "ExternalEvents")
        {
            return;
        }

        var payload = eventData.Payload!;
        var payloadCount = payload.Count;

        switch (eventData.EventId)
        {
            case 1:
                OnEvent1();
                break;

            case 2:
                OnEvent2();
                break;

            case 3:
                OnEvent3();
                break;
        }

        void OnEvent1()
        {
            if (payloadCount != 2)
            {
                this.OnPayloadCountMismatch(
                    eventData,
                    new()
                    {
                        ExpectedCount = 2,
                        ActualCount = payloadCount,

                        // ExpectedVersion はスキーマの EventAttribute.Version がセットされている場合にジェネレーターが入れる
                        ExpectedVersion = 0,
                        ActualVersion = eventData.Version
                    });
            }

            int argument0 = default!;
            int argument1 = default!;

            if (payloadCount >= 1)
            {
                if (payload[0] is int payload0)
                {
                    argument0 = payload0;
                }
                else
                {
                    this.OnPayloadTypeMismatch(eventData, 1);
                    return;
                }
            }

            if (payloadCount >= 2)
            {
                if (payload[1] is int payload1)
                {
                    argument1 = payload1;
                }
                else
                {
                    this.OnPayloadTypeMismatch(eventData, 2);
                    return;
                }
            }

            this.Foo(eventData, argument0, argument1);
        }

        void OnEvent2()
        {
            // 省略
        }

        void OnEvent3()
        {
            // 省略
        }
    }

    [GeneratedEventHandler]
    partial void Foo(EventWrittenEventArgs eventData, int i1, int i2);

    [GeneratedEventHandler]
    partial void Bar(EventWrittenEventArgs eventData, string s, int i, byte[] b);

    [GeneratedEventHandler]
    partial void Baz(EventWrittenEventArgs eventData);

    // ペイロードの内容がキャストできない場合に呼ばれる。
    partial void OnPayloadTypeMismatch(EventWrittenEventArgs eventData, int payloadIndex);

    // ペイロードの数が異なる場合に呼ばれる。
    partial void OnPayloadCountMismatch(EventWrittenEventArgs eventData, PayloadCountMismatchedEventArgs args);

    public sealed class PayloadCountMismatchedEventArgs
    {
        public int ExpectedCount { get; set; }

        public int ActualCount { get; set; }

        public byte? ExpectedVersion { get; set; }

        public byte ActualVersion { get; set; }
    }
}
