// <auto-generated/>

using System.Diagnostics;

namespace GeneratedCode;

[Conditional("COMPILE_TIME_ONLY")]
[AttributeUsage(AttributeTargets.Class)]
public sealed class GeneratedEventListenerAttribute : Attribute
{
    public GeneratedEventListenerAttribute(
        string eventSourceName,
        Type eventSchema)
    {
        this.EventSourceName = eventSourceName;

        this.EventSchema = eventSchema;
    }

    public string EventSourceName { get; }

    public Type EventSchema { get; }
}
