using System;
using System.Threading;
using System.Threading.Tasks;

using Shouldly;

using Aetos.EventSourceToolkit.SourceGenerators;
using Aetos.EventSourceToolkit.Tests.TestUtilities;

namespace Aetos.EventSourceToolkit.Tests.SourceGenerators;

[TestClass]
public sealed class EventSourceGeneratorTest
{
    [TestMethod]
    public async Task 引数がないイベントメソッドの場合()
    {
        /* lang=c# */
        const string Code =
            """
            using System.Diagnostics.Tracing;

            using Aetos.EventSourceToolkit;

            namespace Sample;

            [GeneratedEventSource]
            partial class TestEventSource : EventSource
            {
                [Event(1, Level = EventLevel.Informational)]
                public partial void Foo();
            }
            """;

        /* lang=c# */
        const string ExpectedCode =
            """
            // <auto-generated>

            namespace Sample
            {
                partial class TestEventSource
                {
                    [global::System.Diagnostics.CodeAnalysis.UnconditionalSuppressMessage(
                        "ReflectionAnalysis",
                        "IL2026:RequiresUnreferencedCode",
                        Justification = "Parameters to this method are primitive and are trimmer safe")]
                    public partial void Foo()
                    {
                        if (!this.IsEnabled(global::System.Diagnostics.Tracing.EventLevel.Informational, global::System.Diagnostics.Tracing.EventKeywords.None))
                        {
                            return;
                        }

                        unsafe
                        {
                            this.WriteEventWithRelatedActivityIdCore(1, null, 0, null);
                        }
                    }
                }
            }

            """;

        var result = await RunGeneratorAsync(Code, this._testContext.CancellationToken).ConfigureAwait(false);

        var generatedSource = result.GetGeneratedText("Sample.TestEventSource.Foo.g.cs");

        generatedSource.ShouldBe(ExpectedCode);
    }

    [TestMethod]
    public async Task いろんな型の引数を並べてみる()
    {
        /* lang=c# */
        const string Code =
            """
            using System;
            using System.Diagnostics.Tracing;

            using Aetos.EventSourceToolkit;

            namespace Sample;

            [GeneratedEventSource]
            partial class TestEventSource : EventSource
            {
                public static class Keywords
                {
                    public const EventKeywords A = (EventKeywords)1;
                    public const EventKeywords B = (EventKeywords)2;
                    public const EventKeywords C = (EventKeywords)4;
                }

                [Event(1, Keywords = Keywords.A | Keywords.C)]
                public partial void Foo(
                    Guid relatedActivityId,
                    bool p0, byte p1, sbyte p2, char p3, short p4, ushort p5, int p6, uint p7, long p8, ulong p9,
                    float p10, double p11, string p12, DateTime p13, Guid p14, decimal p15, IntPtr p16, byte[] p17,
                    E p18);

                public enum E { A }
            }
            """;

        /* lang=c# */
        const string ExpectedCode =
            """
            // <auto-generated>

            namespace Sample
            {
                partial class TestEventSource
                {
                    [global::System.Diagnostics.CodeAnalysis.UnconditionalSuppressMessage(
                        "ReflectionAnalysis",
                        "IL2026:RequiresUnreferencedCode",
                        Justification = "Parameters to this method are primitive and are trimmer safe")]
                    public partial void Foo(
                        global::System.Guid relatedActivityId,
                        global::System.Boolean p0,
                        global::System.Byte p1,
                        global::System.SByte p2,
                        global::System.Char p3,
                        global::System.Int16 p4,
                        global::System.UInt16 p5,
                        global::System.Int32 p6,
                        global::System.UInt32 p7,
                        global::System.Int64 p8,
                        global::System.UInt64 p9,
                        global::System.Single p10,
                        global::System.Double p11,
                        global::System.String p12,
                        global::System.DateTime p13,
                        global::System.Guid p14,
                        global::System.Decimal p15,
                        global::System.IntPtr p16,
                        global::System.Byte[] p17,
                        global::Sample.TestEventSource.E p18)
                    {
                        if (!this.IsEnabled(global::System.Diagnostics.Tracing.EventLevel.Informational, global::Sample.TestEventSource.Keywords.A | global::Sample.TestEventSource.Keywords.C))
                        {
                            return;
                        }

                        unsafe
                        {
                            global::System.Diagnostics.Tracing.EventSource.EventData *data = stackalloc global::System.Diagnostics.Tracing.EventSource.EventData[20];

                            p12 ??= "";
                            fixed (global::System.Char *__arg12Pointer = p12)
                            fixed (global::System.Byte *__arg17Pointer = p17)
                            {
                                int __arg0Value = p0 ? 1 : 0;
                                data[0].DataPointer = (global::System.IntPtr)(&__arg0Value);
                                data[0].Size = 4;

                                data[1].DataPointer = (global::System.IntPtr)(&p1);
                                data[1].Size = 1;

                                data[2].DataPointer = (global::System.IntPtr)(&p2);
                                data[2].Size = 1;

                                data[3].DataPointer = (global::System.IntPtr)(&p3);
                                data[3].Size = 2;

                                data[4].DataPointer = (global::System.IntPtr)(&p4);
                                data[4].Size = 2;

                                data[5].DataPointer = (global::System.IntPtr)(&p5);
                                data[5].Size = 2;

                                data[6].DataPointer = (global::System.IntPtr)(&p6);
                                data[6].Size = 4;

                                data[7].DataPointer = (global::System.IntPtr)(&p7);
                                data[7].Size = 4;

                                data[8].DataPointer = (global::System.IntPtr)(&p8);
                                data[8].Size = 8;

                                data[9].DataPointer = (global::System.IntPtr)(&p9);
                                data[9].Size = 8;

                                data[10].DataPointer = (global::System.IntPtr)(&p10);
                                data[10].Size = 4;

                                data[11].DataPointer = (global::System.IntPtr)(&p11);
                                data[11].Size = 8;

                                data[12].DataPointer = (global::System.IntPtr)__arg12Pointer;
                                data[12].Size = (p12.Length + 1) * 2;

                                long __arg13Value = p13.ToFileTimeUtc();
                                data[13].DataPointer = (global::System.IntPtr)(&__arg13Value);
                                data[13].Size = 8;

                                data[14].DataPointer = (global::System.IntPtr)(&p14);
                                data[14].Size = 16;

                                data[15].DataPointer = (global::System.IntPtr)(&p15);
                                data[15].Size = 16;

                                data[16].DataPointer = (global::System.IntPtr)(&p16);
                                data[16].Size = global::System.IntPtr.Size;

                                int __arg17Size = p17 == null ? 0 : p17.Length;
                                data[17].DataPointer = (global::System.IntPtr)(&__arg17Size);
                                data[17].Size = 4;

                                if (__arg17Size == 0)
                                {
                                    data[18].DataPointer = (global::System.IntPtr)(&__arg17Size);
                                    data[18].Size = 0;
                                }
                                else
                                {
                                    data[18].DataPointer = (global::System.IntPtr)__arg17Pointer;
                                    data[18].Size = __arg17Size;
                                }

                                data[19].DataPointer = (global::System.IntPtr)(&p18);
                                data[19].Size = 4;

                                this.WriteEventWithRelatedActivityIdCore(1, &relatedActivityId, 20, data);
                            }
                        }
                    }
                }
            }

            """;

        var result = await RunGeneratorAsync(Code, this._testContext.CancellationToken).ConfigureAwait(false);

        var generatedSource = result.GetGeneratedText("Sample.TestEventSource.Foo.g.cs");

        generatedSource.ShouldBe(ExpectedCode);
    }

    [TestMethod]
    public async Task staticメソッドに対してはコードが生成されない()
    {
        /* lang=c# */
        const string Code =
            """
            using System.Diagnostics.Tracing;

            using Aetos.EventSourceToolkit;

            namespace Sample;

            [GeneratedEventSource]
            partial class TestEventSource : EventSource
            {
                [Event(1, Level = EventLevel.Informational)]
                public static partial void Foo();
            }
            """;

        var result = await RunGeneratorAsync(Code, this._testContext.CancellationToken).ConfigureAwait(false);

        result.GeneratedSources.ShouldNotContain(static x => x.FileName == "Sample.TestEventSource.Foo.g.cs");
    }

    [TestMethod]
    public async Task 型にGeneratedEventSourceAttributeがついていなければコードが生成されない()
    {
        /* lang=c# */
        const string Code =
            """
            using System.Diagnostics.Tracing;

            namespace Sample;

            partial class TestEventSource : EventSource
            {
                [Event(1, Level = EventLevel.Informational)]
                public static partial void {|CS8795:Foo|}();
            }
            """;

        var result = await RunGeneratorAsync(Code, this._testContext.CancellationToken).ConfigureAwait(false);

        result.GeneratedSources.ShouldNotContain(static x => x.FileName == "Sample.TestEventSource.Foo.g.cs");
    }

    [TestMethod]
    public async Task 型がEventSourceから派生していなければコードが生成されない()
    {
        /* lang=c# */
        const string Code =
            """
            using System.Diagnostics.Tracing;

            namespace Sample;

            partial class TestEventSource
            {
                [Event(1, Level = EventLevel.Informational)]
                public static partial void {|CS8795:Foo|}();
            }
            """;

        var result = await RunGeneratorAsync(Code, this._testContext.CancellationToken).ConfigureAwait(false);

        result.GeneratedSources.ShouldNotContain(static x => x.FileName == "Sample.TestEventSource.Foo.g.cs");
    }

    [TestMethod]
    public async Task 型がabstractの場合はコードが生成されない()
    {
        /* lang=c# */
        const string Code =
            """
            using System.Diagnostics.Tracing;

            namespace Sample;

            abstract partial class TestEventSource
            {
                [Event(1, Level = EventLevel.Informational)]
                public static partial void {|CS8795:Foo|}();
            }
            """;

        var result = await RunGeneratorAsync(Code, this._testContext.CancellationToken).ConfigureAwait(false);

        result.GeneratedSources.ShouldNotContain(static x => x.FileName == "Sample.TestEventSource.Foo.g.cs");
    }


    public EventSourceGeneratorTest(
        TestContext testContext)
    {
        ArgumentNullException.ThrowIfNull(testContext);

        this._testContext = testContext;
    }

    private static async Task<GeneratorTestResult> RunGeneratorAsync(
        string inputCode,
        CancellationToken cancellationToken)
    {
        var runner = new CSharpGeneratorRunner(new EventSourceGenerator());

        runner.AddSource("main.cs", inputCode);

        return await runner.RunAsync(cancellationToken).ConfigureAwait(false);
    }

    private readonly TestContext _testContext;
}
