using System;
using System.IO;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;

using Basic.Reference.Assemblies;

using Shouldly;

namespace Aetos.Tracing.Tests;

[TestClass]
public sealed class GeneratedEventSourceTest
{
    [TestMethod]
    public async Task Foo()
    {
        const string Code =
            """
            using System.Diagnostics.Tracing;

            using Aetos.Tracing;

            namespace Sample;

            [EventSource(Name = "TestEventSource")]
            [GeneratedEventSource]
            partial class TestEventSource : EventSource
            {
                [Event(1)]
                public partial void Foo(int i);
            }
            """;

        const string ExpectedCode =
            """
            // <auto-generated>

            namespace Sample
            {
                partial class TestEventSource
                {
                    public partial void Foo(
                        int i)
                    {
                        if (this.IsEnabled(global::System.Diagnostics.Tracing.EventLevel.Informational))
                        {
                        }
                    }
                }
            }

            """;

        var testCancellationToken = this._testContext.CancellationToken;

        var parseOptions = CSharpParseOptions.Default;

        var compilationOptions = new CSharpCompilationOptions(
            OutputKind.DynamicallyLinkedLibrary,
            nullableContextOptions: NullableContextOptions.Enable);

        var driverOptions = new GeneratorDriverOptions(
            trackIncrementalGeneratorSteps: true);

        var syntaxTree = CSharpSyntaxTree.ParseText(Code, parseOptions, "main.cs", Encoding.UTF8, testCancellationToken);

        var compilation = CSharpCompilation.Create(
            "test",
            [syntaxTree],
            Net100.References.All,
            compilationOptions);

        var driver = (GeneratorDriver)CSharpGeneratorDriver.Create(
            [new TraceEventGenerator().AsSourceGenerator()],
            parseOptions: parseOptions,
            driverOptions: driverOptions);

        driver = driver.RunGenerators(compilation, testCancellationToken);

        var runResult = driver.GetRunResult();

        var generatedTree = runResult.GeneratedTrees
            .Single(static x => Path.GetFileName(x.FilePath) == "Sample.TestEventSource.Foo.g.cs");

        var text = await generatedTree.GetTextAsync(testCancellationToken).ConfigureAwait(false);
        var actualText = text.ToString();

        actualText.ShouldBe(ExpectedCode, StringCompareShould.IgnoreLineEndings);
    }

    public GeneratedEventSourceTest(
        TestContext testContext)
    {
        ArgumentNullException.ThrowIfNull(testContext);

        this._testContext = testContext;
    }

    private readonly TestContext _testContext;
}
