using System;
using System.IO;
using System.Linq;
using System.Text;
using System.Threading;
using System.Threading.Tasks;

using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;

using Basic.Reference.Assemblies;

using Shouldly;

namespace Aetos.Tracing.Tests;

[TestClass]
public sealed class GeneratedEventSourceTest
{
    [TestMethod]
    public async Task 引数がないイベントメソッドの場合()
    {
        const string Code =
            """
            using System.Diagnostics.Tracing;

            using Aetos.Tracing;

            namespace Sample;

            [EventSource(Name = "TestEventSource")]
            [GeneratedEventSource]
            partial class TestEventSource : EventSource
            {
                [Event(1, Level = EventLevel.Informational)]
                public partial void Foo();
            }
            """;

        const string ExpectedCode =
            """
            // <auto-generated>

            namespace Sample
            {
                partial class TestEventSource
                {
                    public partial void Foo()
                    {
                        if (!this.IsEnabled(global::System.Diagnostics.Tracing.EventLevel.Informational, global::System.Diagnostics.Tracing.EventKeywords.None))
                        {
                            return;
                        }

                        unsafe
                        {
                            this.WriteEventCore(1, 0, null);
                        }
                    }
                }
            }

            """;

        await ValidateGeneratedCodeAsync(Code, "Sample.TestEventSource.Foo.g.cs", ExpectedCode, this._testContext.CancellationToken).ConfigureAwait(false);
    }

    [TestMethod]
    public async Task いろんな型の引数を並べてみる()
    {
        const string Code =
            """
            using System;
            using System.Diagnostics.Tracing;

            using Aetos.Tracing;

            namespace Sample;

            [EventSource(Name = "TestEventSource")]
            [GeneratedEventSource]
            partial class TestEventSource : EventSource
            {
                public static class Keywords
                {
                    public const EventKeywords A = (EventKeywords)1;
                    public const EventKeywords B = (EventKeywords)2;
                    public const EventKeywords C = (EventKeywords)4;
                }

                [Event(1, Keywords = Keywords.A | Keywords.C)]
                public partial void Foo(
                    bool p0, byte p1, sbyte p2, char p3, short p4, ushort p5, int p6, uint p7, long p8, ulong p9,
                    float p10, double p11, string p12, DateTime p13, Guid p14, decimal p15, IntPtr p16, byte[] p17,
                    E p18);

                public enum E { A }
            }
            """;

        const string ExpectedCode =
            """
            // <auto-generated>

            namespace Sample
            {
                partial class TestEventSource
                {
                    public partial void Foo(
                        global::System.Boolean p0,
                        global::System.Byte p1,
                        global::System.SByte p2,
                        global::System.Char p3,
                        global::System.Int16 p4,
                        global::System.UInt16 p5,
                        global::System.Int32 p6,
                        global::System.UInt32 p7,
                        global::System.Int64 p8,
                        global::System.UInt64 p9,
                        global::System.Single p10,
                        global::System.Double p11,
                        global::System.String p12,
                        global::System.DateTime p13,
                        global::System.Guid p14,
                        global::System.Decimal p15,
                        global::System.IntPtr p16,
                        global::System.Byte[] p17,
                        global::Sample.TestEventSource.E p18)
                    {
                        if (!this.IsEnabled(global::System.Diagnostics.Tracing.EventLevel.Informational, global::Sample.TestEventSource.Keywords.A | global::Sample.TestEventSource.Keywords.C))
                        {
                            return;
                        }

                        unsafe
                        {
                            global::System.Diagnostics.Tracing.EventSource.EventData *data = stackalloc global::System.Diagnostics.Tracing.EventSource.EventData[20];

                            int __arg0Value = p0 ? 1 : 0;
                            data[0].DataPointer = (global::System.IntPtr)(&__arg0Value);
                            data[0].Size = 4;

                            data[1].DataPointer = (global::System.IntPtr)(&p1);
                            data[1].Size = 1;

                            data[2].DataPointer = (global::System.IntPtr)(&p2);
                            data[2].Size = 1;

                            data[3].DataPointer = (global::System.IntPtr)(&p3);
                            data[3].Size = 2;

                            data[4].DataPointer = (global::System.IntPtr)(&p4);
                            data[4].Size = 2;

                            data[5].DataPointer = (global::System.IntPtr)(&p5);
                            data[5].Size = 2;

                            data[6].DataPointer = (global::System.IntPtr)(&p6);
                            data[6].Size = 4;

                            data[7].DataPointer = (global::System.IntPtr)(&p7);
                            data[7].Size = 4;

                            data[8].DataPointer = (global::System.IntPtr)(&p8);
                            data[8].Size = 8;

                            data[9].DataPointer = (global::System.IntPtr)(&p9);
                            data[9].Size = 8;

                            data[10].DataPointer = (global::System.IntPtr)(&p10);
                            data[10].Size = 4;

                            data[11].DataPointer = (global::System.IntPtr)(&p11);
                            data[11].Size = 8;

                            p12 ??= "";
                            fixed (char *__arg12Value = p12)
                            {
                                data[12].DataPointer = (global::System.IntPtr)__arg12Value;
                                data[12].Size = (p12.Length + 1) * 2;
                            }

                            long __arg13Value = p13.ToFileTimeUtc();
                            data[13].DataPointer = (global::System.IntPtr)(&__arg13Value);
                            data[13].Size = 8;

                            data[14].DataPointer = (global::System.IntPtr)(&p14);
                            data[14].Size = 16;

                            data[15].DataPointer = (global::System.IntPtr)(&p15);
                            data[15].Size = 16;

                            data[16].DataPointer = (global::System.IntPtr)(&p16);
                            data[16].Size = global::System.IntPtr.Size;

                            if (p17 == null || p17.Length == 0)
                            {
                                int blobSize = 0;
                                data[17].DataPointer = (global::System.IntPtr)(&blobSize);
                                data[17].Size = 4;
                                data[18].DataPointer = (global::System.IntPtr)(&blobSize);
                                data[18].Size = 0;
                            }
                            else
                            {
                                int blobSize = p17.Length;
                                fixed (byte *blob = &p17[0])
                                {
                                    data[17].DataPointer = (global::System.IntPtr)(&blobSize);
                                    data[17].Size = 4;
                                    data[18].DataPointer = (global::System.IntPtr)blob;
                                    data[18].Size = blobSize;
                                }
                            }

                            data[19].DataPointer = (global::System.IntPtr)(&p18);
                            data[19].Size = 4;

                            this.WriteEventCore(1, 20, data);
                        }
                    }
                }
            }

            """;

        await ValidateGeneratedCodeAsync(Code, "Sample.TestEventSource.Foo.g.cs", ExpectedCode, this._testContext.CancellationToken).ConfigureAwait(false);
    }

    public GeneratedEventSourceTest(
        TestContext testContext)
    {
        ArgumentNullException.ThrowIfNull(testContext);

        this._testContext = testContext;
    }

    private static async Task ValidateGeneratedCodeAsync(
        string inputCode,
        string generatedFileName,
        string expectedGeneratedCode,
        CancellationToken cancellationToken)
    {
        var parseOptions = CSharpParseOptions.Default;

        var compilationOptions = new CSharpCompilationOptions(
            OutputKind.DynamicallyLinkedLibrary,
            allowUnsafe: true,
            nullableContextOptions: NullableContextOptions.Enable);

        var driverOptions = new GeneratorDriverOptions(
            trackIncrementalGeneratorSteps: true);

        var syntaxTree = CSharpSyntaxTree.ParseText(inputCode, parseOptions, "main.cs", Encoding.UTF8, cancellationToken);

        var compilation = CSharpCompilation.Create(
            "test",
            [syntaxTree],
            Net100.References.All,
            compilationOptions);

        var driver = (GeneratorDriver)CSharpGeneratorDriver.Create(
            [new TraceEventGenerator().AsSourceGenerator()],
            parseOptions: parseOptions,
            driverOptions: driverOptions);

        driver = driver.RunGenerators(compilation, cancellationToken);

        var runResult = driver.GetRunResult();

        var generatedTree = runResult.GeneratedTrees
            .Single(x => Path.GetFileName(x.FilePath) == generatedFileName);

        var text = await generatedTree.GetTextAsync(cancellationToken).ConfigureAwait(false);
        var actualText = text.ToString();

        actualText.ShouldBe(expectedGeneratedCode, StringCompareShould.IgnoreLineEndings);
    }

    private readonly TestContext _testContext;
}
