using System.Collections.Generic;
using System.Globalization;
using System.Linq;

using Aetos.EventSourceToolkit.SourceGenerators.Models;

using Microsoft.CodeAnalysis;

namespace Aetos.EventSourceToolkit.SourceGenerators;

internal static class EventSourceEmitter
{
    public static void EmitEventSource(
        SourceProductionContext context,
        EventSourceInfo? methodInfo)
    {
        if (methodInfo is null)
        {
            return;
        }

        var codeBuilder = new IndentedStringBuilder();

        codeBuilder.AppendLineWithIndent("// <auto-generated>");
        codeBuilder.AppendLineWithIndent();

        if (methodInfo.NamespaceSegments.Count != 0)
        {
            var namespaceName = string.Join(".", methodInfo.NamespaceSegments);
            codeBuilder.AppendLineWithIndent($"namespace {namespaceName}");
            codeBuilder.AppendLineWithIndent("{");
            codeBuilder.Indent();
        }

        foreach (var containingType in methodInfo.ContainingTypes)
        {
            codeBuilder.AppendLineWithIndent($"partial {containingType.KindKeyword} {containingType.Name}");
            codeBuilder.AppendLineWithIndent("{");
            codeBuilder.Indent();
        }

        codeBuilder.AppendLineWithIndent($"partial class {methodInfo.ClassName}");
        codeBuilder.AppendLineWithIndent("{");
        codeBuilder.Indent();

        var parameters = methodInfo.Parameters;
        var parameterCount = parameters.Count;
        var hasRelatedActivityIdParameter = methodInfo.HasRelatedActivityIdParameter;

        codeBuilder.AppendLineWithIndent(
            """
            [global::System.Diagnostics.CodeAnalysis.UnconditionalSuppressMessage(
                "ReflectionAnalysis",
                "IL2026:RequiresUnreferencedCode",
                Justification = "Parameters to this method are primitive and are trimmer safe")]
            """);

        codeBuilder.AppendWithIndent($"{methodInfo.AccessibilityKeyword} partial void {methodInfo.MethodName}");

        if (parameterCount == 0)
        {
            if (hasRelatedActivityIdParameter)
            {
                codeBuilder.AppendLineWithIndent("global::System.Guid relatedActivityId)");
            }
            else
            {
                codeBuilder.AppendWithoutIndent("()");
            }

            codeBuilder.AppendLineWithoutIndent();
        }
        else
        {
            codeBuilder.AppendWithoutIndent("(");
            codeBuilder.AppendLineWithoutIndent();
            codeBuilder.Indent();

            if (hasRelatedActivityIdParameter)
            {
                var delimiter = parameterCount != 0 ? "," : ")";
                codeBuilder.AppendLineWithIndent($"global::System.Guid relatedActivityId{delimiter}");
            }

            var parameterEnd = parameterCount - 1;
            for (var i = 0; i <= parameterEnd; ++i)
            {
                var parameter = parameters[i];
                var delimiter = i < parameterEnd ? "," : ")";

                codeBuilder.AppendLineWithIndent($"{parameter.FullyQualifiedTypeName} {parameter.Name}{delimiter}");
            }

            codeBuilder.Unindent();
        }

        codeBuilder.AppendLineWithIndent("{");
        codeBuilder.Indent();

        var metadata = methodInfo.Metadata;
        var eventId = metadata.EventId;
        var eventLevel = metadata.Level;
        var eventKeywords = string.Join(" | ", metadata.Keywords);

        codeBuilder.AppendLineWithIndent(
            $$"""
              if (!this.IsEnabled({{eventLevel}}, {{eventKeywords}}))
              {
              """);
        codeBuilder.Indent();
        codeBuilder.AppendLineWithIndent("return;");
        codeBuilder.Unindent();
        codeBuilder.AppendLineWithIndent("}");
        codeBuilder.AppendLineWithoutIndent();

        codeBuilder.AppendLineWithIndent(
            """
            unsafe
            {
            """);
        codeBuilder.Indent();

        if (parameterCount == 0)
        {
            codeBuilder.AppendLineWithIndent($"this.WriteEventWithRelatedActivityIdCore({eventId}, null, 0, null);");
        }
        else
        {
            // string パラメーターに null の場合の既定値を設定
            foreach (var parameter in parameters)
            {
                if (parameter.FullyQualifiedTypeName != "global::System.String")
                {
                    continue;
                }

                codeBuilder.AppendLineWithIndent($"{parameter.Name} ??= null;");
            }

            codeBuilder.AppendLineWithIndent();

            var byteArrayParameterCount = parameters.Count(static x => x.FullyQualifiedTypeName == "global::System.Byte[]");

            var dataEntryCount = parameterCount + byteArrayParameterCount;
            var parameterStart = 0;
            var relatedActivityIdExpression = "null";

            if (hasRelatedActivityIdParameter)
            {
                relatedActivityIdExpression = "&relatedActivityId";
                parameterStart = 1;
                --dataEntryCount;
            }

            codeBuilder.AppendLineWithIndent($"global::System.Diagnostics.Tracing.EventSource.EventData *data = stackalloc global::System.Diagnostics.Tracing.EventSource.EventData[{dataEntryCount}];");
            codeBuilder.AppendLineWithoutIndent();

            for (int i = parameterStart, j = 0, k = 0; i < parameterCount; ++i)
            {
                var (typeName, parameterName, isEnum, size) = parameters[i];
                var sizeExpression = size?.ToString(CultureInfo.InvariantCulture);

                if (isEnum)
                {
                    WriteData(codeBuilder, j, parameterName, sizeExpression!);
                    continue;
                }

                var temporaryValueParameterName = $"__arg{k}Value";

                switch (typeName)
                {
                    case "global::System.Boolean":
                        codeBuilder.AppendLineWithIndent($"int {temporaryValueParameterName} = {parameterName} ? 1 : 0;");
                        WriteData(codeBuilder, j, temporaryValueParameterName, "4");
                        break;

                    case "global::System.Byte":
                    case "global::System.SByte":
                    case "global::System.Char":
                    case "global::System.Int16":
                    case "global::System.UInt16":
                    case "global::System.Int32":
                    case "global::System.UInt32":
                    case "global::System.Single":
                    case "global::System.Int64":
                    case "global::System.UInt64":
                    case "global::System.Double":
                    case "global::System.Guid":
                    case "global::System.Decimal":
                        WriteData(codeBuilder, j, parameterName, sizeExpression!);
                        break;

                    case "global::System.String":
                        codeBuilder.AppendLineWithIndent(
                            $$"""
                              {{parameterName}} ??= "";
                              fixed (char *{{temporaryValueParameterName}} = {{parameterName}})
                              {
                              """);
                        codeBuilder.Indent();
                        codeBuilder.AppendLineWithIndent(
                            $$"""
                              data[{{j}}].DataPointer = (global::System.IntPtr){{temporaryValueParameterName}};
                              data[{{j}}].Size = ({{parameterName}}.Length + 1) * 2;
                              """);
                        codeBuilder.Unindent();
                        codeBuilder.AppendLineWithIndent(
                            """
                            }
                            """);
                        codeBuilder.AppendLineWithoutIndent();
                        break;

                    case "global::System.DateTime":
                        codeBuilder.AppendLineWithIndent($"long {temporaryValueParameterName} = {parameterName}.ToFileTimeUtc();");
                        WriteData(codeBuilder, j, temporaryValueParameterName, "8");
                        break;

                    case "global::System.IntPtr":
                        WriteData(codeBuilder, j, parameterName, "global::System.IntPtr.Size");
                        break;

                    case "global::System.Byte[]":
                        codeBuilder.AppendLineWithIndent(
                            $$"""
                              if ({{parameterName}} == null || {{parameterName}}.Length == 0)
                              {
                              """);
                        codeBuilder.Indent();
                        codeBuilder.AppendLineWithIndent(
                            $$"""
                              int blobSize = 0;
                              data[{{j}}].DataPointer = (global::System.IntPtr)(&blobSize);
                              data[{{j}}].Size = 4;
                              """);
                        codeBuilder.AppendLineWithIndent($"data[{j + 1}].DataPointer = (global::System.IntPtr)(&blobSize);");
                        codeBuilder.AppendLineWithIndent($"data[{j + 1}].Size = 0;");
                        codeBuilder.Unindent();
                        codeBuilder.AppendLineWithIndent(
                            """
                            }
                            else
                            {
                            """);
                        codeBuilder.Indent();
                        codeBuilder.AppendLineWithIndent(
                            $$"""
                              int blobSize = {{parameterName}}.Length;
                              fixed (byte *blob = &{{parameterName}}[0])
                              {
                              """);
                        codeBuilder.Indent();
                        codeBuilder.AppendLineWithIndent(
                            $$"""
                              data[{{j}}].DataPointer = (global::System.IntPtr)(&blobSize);
                              data[{{j}}].Size = 4;
                              data[{{j + 1}}].DataPointer = (global::System.IntPtr)blob;
                              data[{{j + 1}}].Size = blobSize;
                              """);
                        codeBuilder.Unindent();
                        codeBuilder.AppendLineWithIndent(
                            """
                            }
                            """);
                        codeBuilder.Unindent();
                        codeBuilder.AppendLineWithIndent(
                            """
                            }
                            """);
                        codeBuilder.AppendLineWithoutIndent();
                        ++j;
                        break;
                }

                ++j;
                ++k;
            }

            codeBuilder.AppendLineWithIndent($"this.WriteEventWithRelatedActivityIdCore({eventId}, {relatedActivityIdExpression}, {dataEntryCount}, data);");
        }

        // method
        codeBuilder.Unindent();
        codeBuilder.AppendLineWithIndent("}");

        // class
        codeBuilder.Unindent();
        codeBuilder.AppendLineWithIndent("}");

        // enclosing class and namespace
        while (codeBuilder.IndentationLevel != 0)
        {
            codeBuilder.Unindent();
            codeBuilder.AppendLineWithIndent("}");
        }

        var code = codeBuilder.ToString();

        var fileNameSegments = new List<string>();

        fileNameSegments.AddRange(methodInfo.NamespaceSegments);
        fileNameSegments.AddRange(methodInfo.ContainingTypes.Select(static x => x.Name));
        fileNameSegments.Add(methodInfo.ClassName);
        fileNameSegments.Add(methodInfo.MethodName);
        fileNameSegments.Add("g.cs");

        var fileName = string.Join(".", fileNameSegments);

        context.AddSource(fileName, code);

        static void WriteData(
            IndentedStringBuilder codeBuilder,
            int dataEntryIndex,
            string parameterName,
            string parameterSizeExpression)
        {
            codeBuilder.AppendLineWithIndent($"data[{dataEntryIndex}].DataPointer = (global::System.IntPtr)(&{parameterName});");
            codeBuilder.AppendLineWithIndent($"data[{dataEntryIndex}].Size = {parameterSizeExpression};");
            codeBuilder.AppendLineWithoutIndent();
        }
    }
}
