using Microsoft.CodeAnalysis;

namespace Aetos.EventSourceToolkit.SourceGenerators;

public partial class EventSourceGenerator
{
    // lang=c#
    private const string GeneratedEventSourceAttributeCode =
        """
        // <auto-generated/>

        namespace Aetos.EventSourceToolkit
        {
            [global::Microsoft.CodeAnalysis.Embedded]
            [global::System.AttributeUsage(global::System.AttributeTargets.Class)]
            [global::System.Diagnostics.Conditional("COMPILE_TIME_ONLY")]
            internal sealed class GeneratedEventSourceAttribute : global::System.Attribute
            {
            }
        }
        """;

    public static void PostInitialize(
        IncrementalGeneratorPostInitializationContext context)
    {
        context.AddEmbeddedAttributeDefinition();

        context.AddSource(
            "Aetos.EventSourceToolkit.GeneratedEventSourceAttribute.g.cs",
            GeneratedEventSourceAttributeCode);
    }
}
