using System.Collections.Generic;
using System.Globalization;
using System.Linq;

using Microsoft.CodeAnalysis;

using Aetos.EventSourceToolkit.SourceGenerators.Models;

namespace Aetos.EventSourceToolkit.SourceGenerators;

internal static class EventSourceEmitter
{
    public static void EmitEventSource(
        SourceProductionContext context,
        EventSourceMethodInfo? methodInfo)
    {
        if (methodInfo is null)
        {
            return;
        }

        var codeBuilder = new IndentedStringBuilder();

        codeBuilder.AppendLine("// <auto-generated>");
        codeBuilder.AppendLine();

        var declarations = GetEnclosingDeclarations(methodInfo);

        EmitEnclosingDeclarations(codeBuilder, declarations, 0, methodInfo);

        var code = codeBuilder.Build();
        var fileName = GetFileName(methodInfo);

        context.AddSource(fileName, code);
    }

    /// <summary>
    /// イベント メソッドを囲む宣言のヘッダーを、外側から内側の順に並べて返す。
    /// </summary>
    private static List<string> GetEnclosingDeclarations(
        EventSourceMethodInfo methodInfo)
    {
        var declarations = new List<string>();

        if (methodInfo.NamespaceSegments.Count != 0)
        {
            declarations.Add($"namespace {string.Join(".", methodInfo.NamespaceSegments)}");
        }

        foreach (var containingType in methodInfo.ContainingTypes)
        {
            declarations.Add($"partial {containingType.KindKeyword} {containingType.Name}");
        }

        declarations.Add($"partial class {methodInfo.ClassName}");

        return declarations;
    }

    private static void EmitEnclosingDeclarations(
        IndentedStringBuilder codeBuilder,
        List<string> declarations,
        int index,
        EventSourceMethodInfo methodInfo)
    {
        if (index == declarations.Count)
        {
            EmitMethod(codeBuilder, methodInfo);
            return;
        }

        using (codeBuilder.Block(declarations[index]))
        {
            EmitEnclosingDeclarations(codeBuilder, declarations, index + 1, methodInfo);
        }
    }

    private static void EmitMethod(
        IndentedStringBuilder codeBuilder,
        EventSourceMethodInfo methodInfo)
    {
        codeBuilder.AppendLine(
            """
            [global::System.Diagnostics.CodeAnalysis.UnconditionalSuppressMessage(
                "ReflectionAnalysis",
                "IL2026:RequiresUnreferencedCode",
                Justification = "Parameters to this method are primitive and are trimmer safe")]
            """);

        EmitMethodSignature(codeBuilder, methodInfo);

        using (codeBuilder.Block())
        {
            EmitMethodBody(codeBuilder, methodInfo);
        }
    }

    private static void EmitMethodSignature(
        IndentedStringBuilder codeBuilder,
        EventSourceMethodInfo methodInfo)
    {
        codeBuilder.Append($"{methodInfo.AccessibilityKeyword} partial void {methodInfo.MethodName}");

        var parameters = methodInfo.Parameters;
        var hasRelatedActivityIdParameter = methodInfo.HasRelatedActivityIdParameter;

        if (parameters.Count == 0)
        {
            if (hasRelatedActivityIdParameter)
            {
                codeBuilder.AppendLine("(");
                using (codeBuilder.Indent())
                {
                    codeBuilder.AppendLine("global::System.Guid relatedActivityId)");
                }
            }
            else
            {
                codeBuilder.AppendLine("()");
            }

            return;
        }

        codeBuilder.AppendLine("(");

        using (codeBuilder.Indent())
        {
            if (hasRelatedActivityIdParameter)
            {
                codeBuilder.AppendLine("global::System.Guid relatedActivityId,");
            }

            var parameterEnd = parameters.Count - 1;

            for (var i = 0; i <= parameterEnd; ++i)
            {
                var parameter = parameters[i];
                var delimiter = i < parameterEnd ? "," : ")";

                codeBuilder.AppendLine($"{parameter.FullyQualifiedTypeName} {parameter.Name}{delimiter}");
            }
        }
    }

    private static void EmitMethodBody(
        IndentedStringBuilder codeBuilder,
        EventSourceMethodInfo methodInfo)
    {
        var metadata = methodInfo.Metadata;
        var eventKeywords = string.Join(" | ", metadata.Keywords);

        using (codeBuilder.Block($"if (!this.IsEnabled({metadata.Level}, {eventKeywords}))"))
        {
            codeBuilder.AppendLine("return;");
        }

        codeBuilder.AppendLine();

        using (codeBuilder.Block("unsafe"))
        {
            EmitWriteEvent(codeBuilder, methodInfo);
        }
    }

    private static void EmitWriteEvent(
        IndentedStringBuilder codeBuilder,
        EventSourceMethodInfo methodInfo)
    {
        var parameters = methodInfo.Parameters;
        var eventId = methodInfo.Metadata.EventId;

        // relatedActivityId はペイロードではなく WriteEventWithRelatedActivityIdCore の引数として渡す
        var relatedActivityIdExpression =
            methodInfo.HasRelatedActivityIdParameter ? "&relatedActivityId" : "null";

        if (parameters.Count == 0)
        {
            codeBuilder.AppendLine(
                $"this.WriteEventWithRelatedActivityIdCore({eventId}, {relatedActivityIdExpression}, 0, null);");

            return;
        }

        // byte[] は長さと本体で 2 エントリを使う
        var byteArrayParameterCount = parameters.Count(
            static x => x.FullyQualifiedTypeName == "global::System.Byte[]");

        var dataEntryCount = parameters.Count + byteArrayParameterCount;

        codeBuilder.AppendLine($"global::System.Diagnostics.Tracing.EventSource.EventData *data = stackalloc global::System.Diagnostics.Tracing.EventSource.EventData[{dataEntryCount}];");
        codeBuilder.AppendLine();

        EmitStringParameterInitializations(codeBuilder, parameters);

        var fixedStatements = GetFixedStatements(parameters);

        using (codeBuilder.BlockIf(fixedStatements is not null, fixedStatements))
        {
            var dataEntryIndex = 0;

            for (var i = 0; i < parameters.Count; ++i)
            {
                dataEntryIndex += EmitParameterDataEntries(
                    codeBuilder,
                    parameters[i],
                    dataEntryIndex,
                    GetTemporaryNamePrefix(i));
            }

            codeBuilder.AppendLine(
                $"this.WriteEventWithRelatedActivityIdCore({eventId}, {relatedActivityIdExpression}, {dataEntryCount}, data);");
        }
    }

    private static void EmitStringParameterInitializations(
        IndentedStringBuilder codeBuilder,
        IEnumerable<EventSourceMethodParameterInfo> parameters)
    {
        foreach (var parameter in parameters)
        {
            if (parameter.FullyQualifiedTypeName != "global::System.String")
            {
                continue;
            }

            codeBuilder.AppendLine($"{parameter.Name} ??= \"\";");
        }
    }

    private static bool RequiresPinning(EventSourceMethodParameterInfo parameter)
    {
        var type = parameter.FullyQualifiedTypeName;

        return type is "global::System.String" or "global::System.Byte[]";
    }

    /// <summary>
    /// 固定が必要なパラメーターに対する fixed ステートメントを改行区切りで連結して返す。
    /// 固定が必要なパラメーターがない場合は <see langword="null" />。
    /// </summary>
    private static string? GetFixedStatements(
        EquatableArray<EventSourceMethodParameterInfo> parameters)
    {
        List<string>? statements = null;

        for (var i = 0; i < parameters.Count; ++i)
        {
            var parameter = parameters[i];

            if (!RequiresPinning(parameter))
            {
                continue;
            }

            var pointerType = parameter.FullyQualifiedTypeName == "global::System.String"
                ? "global::System.Char"
                : "global::System.Byte";

            statements ??= [];

            statements.Add(
                $"fixed ({pointerType} *{GetTemporaryNamePrefix(i)}Pointer = {parameter.Name})");
        }

        return statements is null ? null : string.Join("\n", statements);
    }

    private static string GetTemporaryNamePrefix(
        int parameterIndex)
    {
        return $"__arg{parameterIndex}";
    }

    /// <summary>
    /// パラメーター 1 個分の <c>EventData</c> エントリを出力し、消費したエントリ数を返す。
    /// </summary>
    private static int EmitParameterDataEntries(
        IndentedStringBuilder codeBuilder,
        EventSourceMethodParameterInfo parameter,
        int dataEntryIndex,
        string temporaryNamePrefix)
    {
        var (typeName, parameterName, isEnum, fixedSize) = parameter;

        var temporaryValueName = $"{temporaryNamePrefix}Value";

        if (isEnum)
        {
            EmitDataEntry(
                codeBuilder,
                dataEntryIndex,
                parameterName,
                fixedSize!.Value);

            return 1;
        }

        switch (typeName)
        {
            case "global::System.Boolean":
                codeBuilder.AppendLine($"int {temporaryValueName} = {parameterName} ? 1 : 0;");
                EmitDataEntry(codeBuilder, dataEntryIndex, temporaryValueName, 4);
                break;

            case "global::System.Byte":
            case "global::System.SByte":
            case "global::System.Char":
            case "global::System.Int16":
            case "global::System.UInt16":
            case "global::System.Int32":
            case "global::System.UInt32":
            case "global::System.Single":
            case "global::System.Int64":
            case "global::System.UInt64":
            case "global::System.Double":
            case "global::System.Guid":
            case "global::System.Decimal":
                EmitDataEntry(codeBuilder, dataEntryIndex, parameterName, fixedSize!.Value);
                break;

            case "global::System.String":
                // null は EmitStringParameterInitializations で "" に置き換えられている
                EmitDataEntryWithPointer(
                    codeBuilder,
                    dataEntryIndex,
                    $"{temporaryNamePrefix}Pointer",
                    $"({parameterName}.Length + 1) * 2");

                break;

            case "global::System.DateTime":
                codeBuilder.AppendLine($"long {temporaryValueName} = {parameterName}.ToFileTimeUtc();");
                EmitDataEntry(codeBuilder, dataEntryIndex, temporaryValueName, 8);
                break;

            case "global::System.IntPtr":
                EmitDataEntry(codeBuilder, dataEntryIndex, parameterName, "global::System.IntPtr.Size");
                break;

            case "global::System.Byte[]":
            {
                var blobSizeName = $"{temporaryNamePrefix}Size";
                var blobPointerName = $"{temporaryNamePrefix}Pointer";

                codeBuilder.AppendLine(
                    $"int {blobSizeName} = {parameterName} == null ? 0 : {parameterName}.Length;");

                EmitDataEntry(codeBuilder, dataEntryIndex, blobSizeName, 4);

                // null または空の配列では固定されたポインターが null になるため、長さの変数を指しておく
                using (codeBuilder.Block($"if ({blobSizeName} == 0)"))
                {
                    codeBuilder.AppendLine(
                        $$"""
                          data[{{dataEntryIndex + 1}}].DataPointer = (global::System.IntPtr)(&{{blobSizeName}});
                          data[{{dataEntryIndex + 1}}].Size = 0;
                          """);
                }

                using (codeBuilder.Block("else"))
                {
                    codeBuilder.AppendLine(
                        $$"""
                          data[{{dataEntryIndex + 1}}].DataPointer = (global::System.IntPtr){{blobPointerName}};
                          data[{{dataEntryIndex + 1}}].Size = {{blobSizeName}};
                          """);
                }

                codeBuilder.AppendLine();
                return 2;
            }

            default:
                break;
        }

        return 1;
    }

    /// <summary>
    /// 変数のアドレスを指す <c>EventData</c> エントリを出力する。
    /// </summary>
    private static void EmitDataEntry(
        IndentedStringBuilder codeBuilder,
        int dataEntryIndex,
        string valueName,
        string sizeExpression)
    {
        codeBuilder.AppendLine(
            $$"""
              data[{{dataEntryIndex}}].DataPointer = (global::System.IntPtr)(&{{valueName}});
              data[{{dataEntryIndex}}].Size = {{sizeExpression}};
              """);

        codeBuilder.AppendLine();
    }

    private static void EmitDataEntry(
        IndentedStringBuilder codeBuilder,
        int dataEntryIndex,
        string valueName,
        int size)
    {
        EmitDataEntry(codeBuilder, dataEntryIndex, valueName, size.ToString(CultureInfo.InvariantCulture));
    }

    /// <summary>
    /// fixed ステートメントで固定済みのポインターを指す <c>EventData</c> エントリを出力する。
    /// </summary>
    private static void EmitDataEntryWithPointer(
        IndentedStringBuilder codeBuilder,
        int dataEntryIndex,
        string pointerName,
        string sizeExpression)
    {
        codeBuilder.AppendLine(
            $$"""
              data[{{dataEntryIndex}}].DataPointer = (global::System.IntPtr){{pointerName}};
              data[{{dataEntryIndex}}].Size = {{sizeExpression}};
              """);

        codeBuilder.AppendLine();
    }

    private static string GetFileName(
        EventSourceMethodInfo methodInfo)
    {
        var segments = new List<string>();

        segments.AddRange(methodInfo.NamespaceSegments);
        segments.AddRange(methodInfo.ContainingTypes.Select(static x => x.Name));
        segments.Add(methodInfo.ClassName);
        segments.Add(methodInfo.MethodName);
        segments.Add("g.cs");

        return string.Join(".", segments);
    }
}
