using System.Collections.Generic;
using System.Globalization;
using System.Linq;

using Microsoft.CodeAnalysis;

using Aetos.EventSourceToolkit.SourceGenerators.Models;

namespace Aetos.EventSourceToolkit.SourceGenerators;

internal static class EventSourceEmitter
{
    public static void EmitEventSource(
        SourceProductionContext context,
        EventSourceMethodInfo? methodInfo)
    {
        if (methodInfo is null)
        {
            return;
        }

        var codeBuilder = new IndentedStringBuilder();

        codeBuilder.AppendLine("// <auto-generated>");
        codeBuilder.AppendLine();

        var declarations = GetEnclosingDeclarations(methodInfo);

        EmitEnclosingDeclarations(codeBuilder, declarations, 0, methodInfo);

        var code = codeBuilder.Build();
        var fileName = GetFileName(methodInfo);

        context.AddSource(fileName, code);
    }

    /// <summary>
    /// イベント メソッドを囲む宣言のヘッダーを、外側から内側の順に並べて返す。
    /// </summary>
    private static List<string> GetEnclosingDeclarations(
        EventSourceMethodInfo methodInfo)
    {
        var declarations = new List<string>();

        if (methodInfo.NamespaceSegments.Count != 0)
        {
            declarations.Add($"namespace {string.Join(".", methodInfo.NamespaceSegments)}");
        }

        foreach (var containingType in methodInfo.ContainingTypes)
        {
            declarations.Add($"partial {containingType.KindKeyword} {containingType.Name}");
        }

        declarations.Add($"partial class {methodInfo.ClassName}");

        return declarations;
    }

    private static void EmitEnclosingDeclarations(
        IndentedStringBuilder codeBuilder,
        List<string> declarations,
        int index,
        EventSourceMethodInfo methodInfo)
    {
        if (index == declarations.Count)
        {
            EmitMethod(codeBuilder, methodInfo);
            return;
        }

        using (codeBuilder.Block(declarations[index]))
        {
            EmitEnclosingDeclarations(codeBuilder, declarations, index + 1, methodInfo);
        }
    }

    private static void EmitMethod(
        IndentedStringBuilder codeBuilder,
        EventSourceMethodInfo methodInfo)
    {
        codeBuilder.AppendLine(
            """
            [global::System.Diagnostics.CodeAnalysis.UnconditionalSuppressMessage(
                "ReflectionAnalysis",
                "IL2026:RequiresUnreferencedCode",
                Justification = "Parameters to this method are primitive and are trimmer safe")]
            """);

        EmitMethodSignature(codeBuilder, methodInfo);

        using (codeBuilder.Block())
        {
            EmitMethodBody(codeBuilder, methodInfo);
        }
    }

    private static void EmitMethodSignature(
        IndentedStringBuilder codeBuilder,
        EventSourceMethodInfo methodInfo)
    {
        codeBuilder.Append($"{methodInfo.AccessibilityKeyword} partial void {methodInfo.MethodName}");

        var parameters = methodInfo.Parameters;
        var hasRelatedActivityIdParameter = methodInfo.HasRelatedActivityIdParameter;

        if (parameters.Count == 0)
        {
            if (hasRelatedActivityIdParameter)
            {
                codeBuilder.AppendLine("(");
                using (codeBuilder.Indent())
                {
                    codeBuilder.AppendLine("global::System.Guid relatedActivityId)");
                }
            }
            else
            {
                codeBuilder.AppendLine("()");
            }

            return;
        }

        codeBuilder.AppendLine("(");

        using (codeBuilder.Indent())
        {
            if (hasRelatedActivityIdParameter)
            {
                codeBuilder.AppendLine("global::System.Guid relatedActivityId,");
            }

            var parameterEnd = parameters.Count - 1;

            for (var i = 0; i <= parameterEnd; ++i)
            {
                var parameter = parameters[i];
                var delimiter = i < parameterEnd ? "," : ")";

                codeBuilder.AppendLine($"{parameter.FullyQualifiedTypeName} {parameter.Name}{delimiter}");
            }
        }
    }

    private static void EmitMethodBody(
        IndentedStringBuilder codeBuilder,
        EventSourceMethodInfo methodInfo)
    {
        var metadata = methodInfo.Metadata;
        var eventKeywords = string.Join(" | ", metadata.Keywords);

        using (codeBuilder.Block($"if (!this.IsEnabled({metadata.Level}, {eventKeywords}))"))
        {
            codeBuilder.AppendLine("return;");
        }

        codeBuilder.AppendLine();

        using (codeBuilder.Block("unsafe"))
        {
            EmitWriteEvent(codeBuilder, methodInfo);
        }
    }

    private static void EmitWriteEvent(
        IndentedStringBuilder codeBuilder,
        EventSourceMethodInfo methodInfo)
    {
        var parameters = methodInfo.Parameters;
        var eventId = methodInfo.Metadata.EventId;

        // relatedActivityId はペイロードではなく WriteEventWithRelatedActivityIdCore の引数として渡す
        var relatedActivityIdExpression =
            methodInfo.HasRelatedActivityIdParameter ? "&relatedActivityId" : "null";

        if (parameters.Count == 0)
        {
            codeBuilder.AppendLine(
                $"this.WriteEventWithRelatedActivityIdCore({eventId}, {relatedActivityIdExpression}, 0, null);");

            return;
        }

        // byte[] は長さと本体で 2 エントリを使う
        var byteArrayParameterCount = parameters.Count(
            static x => x.FullyQualifiedTypeName == "global::System.Byte[]");

        var dataEntryCount = parameters.Count + byteArrayParameterCount;

        codeBuilder.AppendLine($"global::System.Diagnostics.Tracing.EventSource.EventData *data = stackalloc global::System.Diagnostics.Tracing.EventSource.EventData[{dataEntryCount}];");
        codeBuilder.AppendLine();

        var dataEntryIndex = 0;
        var temporaryValueIndex = 0;

        foreach (var parameter in parameters)
        {
            dataEntryIndex += EmitParameterDataEntries(
                codeBuilder,
                parameter,
                dataEntryIndex,
                $"__arg{temporaryValueIndex}Value");

            ++temporaryValueIndex;
        }

        codeBuilder.AppendLine(
            $"this.WriteEventWithRelatedActivityIdCore({eventId}, {relatedActivityIdExpression}, {dataEntryCount}, data);");
    }

    /// <summary>
    /// パラメーター 1 個分の <c>EventData</c> エントリを出力し、消費したエントリ数を返す。
    /// </summary>
    private static int EmitParameterDataEntries(
        IndentedStringBuilder codeBuilder,
        EventSourceMethodParameterInfo parameter,
        int dataEntryIndex,
        string temporaryValueName)
    {
        var (typeName, parameterName, isEnum, fixedSize) = parameter;
        var sizeExpression = fixedSize?.ToString(CultureInfo.InvariantCulture);

        if (isEnum)
        {
            EmitDataEntry(
                codeBuilder,
                dataEntryIndex,
                parameterName,
                sizeExpression!);

            return 1;
        }

        switch (typeName)
        {
            case "global::System.Boolean":
                codeBuilder.AppendLine($"int {temporaryValueName} = {parameterName} ? 1 : 0;");
                EmitDataEntry(codeBuilder, dataEntryIndex, temporaryValueName, "4");
                break;

            case "global::System.Byte":
            case "global::System.SByte":
            case "global::System.Char":
            case "global::System.Int16":
            case "global::System.UInt16":
            case "global::System.Int32":
            case "global::System.UInt32":
            case "global::System.Single":
            case "global::System.Int64":
            case "global::System.UInt64":
            case "global::System.Double":
            case "global::System.Guid":
            case "global::System.Decimal":
                EmitDataEntry(codeBuilder, dataEntryIndex, parameterName, sizeExpression!);
                break;

            case "global::System.String":
                codeBuilder.AppendLine($$"""{{parameterName}} ??= "";""");

                using (codeBuilder.Block($"fixed (char *{temporaryValueName} = {parameterName})"))
                {
                    codeBuilder.AppendLine(
                        $$"""
                          data[{{dataEntryIndex}}].DataPointer = (global::System.IntPtr){{temporaryValueName}};
                          data[{{dataEntryIndex}}].Size = ({{parameterName}}.Length + 1) * 2;
                          """);
                }

                codeBuilder.AppendLine();
                break;

            case "global::System.DateTime":
                codeBuilder.AppendLine($"long {temporaryValueName} = {parameterName}.ToFileTimeUtc();");
                EmitDataEntry(codeBuilder, dataEntryIndex, temporaryValueName, "8");
                break;

            case "global::System.IntPtr":
                EmitDataEntry(codeBuilder, dataEntryIndex, parameterName, "global::System.IntPtr.Size");
                break;

            case "global::System.Byte[]":
                using (codeBuilder.Block($"if ({parameterName} == null || {parameterName}.Length == 0)"))
                {
                    codeBuilder.AppendLine(
                        $$"""
                          int blobSize = 0;
                          data[{{dataEntryIndex}}].DataPointer = (global::System.IntPtr)(&blobSize);
                          data[{{dataEntryIndex}}].Size = 4;
                          data[{{dataEntryIndex + 1}}].DataPointer = (global::System.IntPtr)(&blobSize);
                          data[{{dataEntryIndex + 1}}].Size = 0;
                          """);
                }

                using (codeBuilder.Block("else"))
                {
                    codeBuilder.AppendLine($"int blobSize = {parameterName}.Length;");

                    using (codeBuilder.Block($"fixed (byte *blob = &{parameterName}[0])"))
                    {
                        codeBuilder.AppendLine(
                            $$"""
                              data[{{dataEntryIndex}}].DataPointer = (global::System.IntPtr)(&blobSize);
                              data[{{dataEntryIndex}}].Size = 4;
                              data[{{dataEntryIndex + 1}}].DataPointer = (global::System.IntPtr)blob;
                              data[{{dataEntryIndex + 1}}].Size = blobSize;
                              """);
                    }
                }

                codeBuilder.AppendLine();
                return 2;
        }

        return 1;
    }

    private static void EmitDataEntry(
        IndentedStringBuilder codeBuilder,
        int dataEntryIndex,
        string valueName,
        string sizeExpression)
    {
        codeBuilder.AppendLine(
            $$"""
              data[{{dataEntryIndex}}].DataPointer = (global::System.IntPtr)(&{{valueName}});
              data[{{dataEntryIndex}}].Size = {{sizeExpression}};
              """);

        codeBuilder.AppendLine();
    }

    private static string GetFileName(
        EventSourceMethodInfo methodInfo)
    {
        var segments = new List<string>();

        segments.AddRange(methodInfo.NamespaceSegments);
        segments.AddRange(methodInfo.ContainingTypes.Select(static x => x.Name));
        segments.Add(methodInfo.ClassName);
        segments.Add(methodInfo.MethodName);
        segments.Add("g.cs");

        return string.Join(".", segments);
    }
}
