using Microsoft.CodeAnalysis;

namespace Aetos.EventSourceToolkit.SourceGenerators;

public partial class EventListenerGenerator
{
    // lang=c#
    private const string GeneratedEventListenerAttributeCode =
        """
        // <auto-generated/>

        namespace Aetos.EventSourceToolkit
        {
            [global::Microsoft.CodeAnalysis.Embedded]
            [global::System.AttributeUsage(global::System.AttributeTargets.Class)]
            [global::System.Diagnostics.Conditional("COMPILE_TIME_ONLY")]
            internal sealed class GeneratedEventListenerAttribute : global::System.Attribute
            {
                public GeneratedEventListenerAttribute(
                    global::System.String eventSourceName,
                    global::System.Type eventSchema)
                {
                    this.EventSourceName = eventSourceName;
                    this.EventSchema = eventSchema;
                }

                public global::System.String EventSourceName { get; }

                public global::System.Type EventSchema { get; }
            }
        }
        """;

    public static void PostInitialize(
        IncrementalGeneratorPostInitializationContext context)
    {
        context.AddEmbeddedAttributeDefinition();

        context.AddSource(
            "Aetos.EventSourceToolkit.GeneratedEventListenerAttribute.g.cs",
            GeneratedEventListenerAttributeCode);
    }
}
