using Microsoft.CodeAnalysis;

using static Aetos.EventSourceToolkit.Constants;

namespace Aetos.EventSourceToolkit.SourceGenerators;

public partial class EventSourceGenerator
{
    internal const string GeneratedEventSourceAttributeCode =
        $$"""
        // <auto-generated/>

        namespace {{Namespace}}
        {
            [global::Microsoft.CodeAnalysis.Embedded]
            [global::System.AttributeUsage(global::System.AttributeTargets.Class)]
            [global::System.Diagnostics.Conditional("COMPILE_TIME_ONLY")]
            internal sealed class {{GeneratedEventSourceAttributeName}} : global::System.Attribute
            {
            }
        }
        """;

    public static void PostInitialize(
        IncrementalGeneratorPostInitializationContext context)
    {
        context.AddEmbeddedAttributeDefinition();

        context.AddSource(GeneratedEventSourceAttributeFileName, GeneratedEventSourceAttributeCode);
    }
}
