<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
    <AssemblyName>Aetos.EventSourceToolkit.SourceGenerators</AssemblyName>
    <RootNamespace>$(AssemblyName)</RootNamespace>
    <IsRoslynComponent>true</IsRoslynComponent>
    <NeutralLanguage>en-US</NeutralLanguage>
    <IncludeCommon>true</IncludeCommon>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Aetos.CSharpPolyfills">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.CodeAnalysis.CSharp">
      <PrivateAssets>all</PrivateAssets>
      <ExcludeAssets>runtime</ExcludeAssets>
    </PackageReference>
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Update="Properties\Resources.ja.resx">
      <Generator></Generator>
    </EmbeddedResource>
    <EmbeddedResource Update="Properties\Resources.resx">
      <Generator></Generator>
    </EmbeddedResource>
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="Aetos.EventSourceToolkit.Tests.SourceGenerators" />
  </ItemGroup>

</Project>
