using System.Collections.Generic;
using System.Linq;

using Microsoft.CodeAnalysis;

using Aetos.Tracing.Models;

using static Aetos.Tracing.Constants;

namespace Aetos.Tracing;

internal static class EventListenerBaseEmitter
{
    public static void EmitEventListenerBase(
        SourceProductionContext context,
        EventSourceMethodInfoWithDiagnostics input)
    {
        if (input.SourceInfo is not { } methodInfo)
        {
            return;
        }

        var codeBuilder = new IndentedStringBuilder();

        codeBuilder.AppendLineWithIndent("// <auto-generated>");
        codeBuilder.AppendLineWithIndent();

        if (methodInfo.NamespaceSegments.Count != 0)
        {
            var namespaceName = string.Join(".", methodInfo.NamespaceSegments);
            codeBuilder.AppendLineWithIndent($"namespace {namespaceName}");
            codeBuilder.AppendLineWithIndent("{");
            codeBuilder.Indent();
        }

        foreach (var containingType in methodInfo.ContainingTypes)
        {
            codeBuilder.AppendLineWithIndent($"partial {containingType.KindKeyword} {containingType.Name}");
            codeBuilder.AppendLineWithIndent("{");
            codeBuilder.Indent();
        }

        codeBuilder.AppendLineWithIndent($"partial class {methodInfo.ClassName}");
        codeBuilder.AppendLineWithIndent("{");
        codeBuilder.Indent();

        codeBuilder.AppendLineWithIndent(
            """
            public abstract partial class ListenerBase : global::System.Diagnostics.Tracing.EventListener
            {
            """);
        codeBuilder.Indent();

        var metadata = methodInfo.Metadata;
        var eventId = metadata.EventId;
        var eventLevel = metadata.Level;
        var eventKeywords = string.Join(" | ", metadata.Keywords);

        codeBuilder.AppendLineWithIndent(
            $"[global::{GeneratedEventAttributeFullName}({eventId}, {eventLevel}, {eventKeywords})]");

        codeBuilder.AppendWithIndent($"protected virtual void {methodInfo.MethodName}");

        var parameters = methodInfo.Parameters;
        var hasRelatedActivityIdParameter = parameters.Count != 0 && parameters[0].IsRelatedActivityIdParameter;

        codeBuilder.AppendWithoutIndent("(");
        codeBuilder.AppendLineWithoutIndent();
        codeBuilder.Indent();

        var delimiter = (parameters.Count == 0 || (parameters.Count == 1 && hasRelatedActivityIdParameter)) ? ")" : ",";
        codeBuilder.AppendLineWithIndent(
            $"global::System.Diagnostics.Tracing.EventWrittenEventArgs args{delimiter}");

        var parameterStart = 0;

        if (hasRelatedActivityIdParameter)
        {
            parameterStart = 1;
        }

        for (var i = parameterStart; i < parameters.Count; ++i)
        {
            var parameter = parameters[i];
            var delimiter2 = i < parameters.Count - 1 ? "," : ")";

            codeBuilder.AppendLineWithIndent($"{parameter.FullyQualifiedTypeName} {parameter.Name}{delimiter2}");
        }

        codeBuilder.Unindent();

        codeBuilder.AppendLineWithIndent("{");
        codeBuilder.Indent();

        // method
        codeBuilder.Unindent();
        codeBuilder.AppendLineWithIndent("}");

        // class
        codeBuilder.Unindent();
        codeBuilder.AppendLineWithIndent(
            """
            }
            """);

        // enclosing class and namespace
        while (codeBuilder.IndentationLevel != 0)
        {
            codeBuilder.Unindent();
            codeBuilder.AppendLineWithIndent("}");
        }

        var code = codeBuilder.ToString();

        var fileNameSegments = new List<string>();

        fileNameSegments.AddRange(methodInfo.NamespaceSegments);
        fileNameSegments.AddRange(methodInfo.ContainingTypes.Select(static x => x.Name));
        fileNameSegments.Add(methodInfo.ClassName);
        fileNameSegments.Add("ListenerBase");
        fileNameSegments.Add(methodInfo.MethodName);
        fileNameSegments.Add(GeneratedFileExtension);

        var fileName = string.Join(".", fileNameSegments);

        context.AddSource(fileName, code);
    }
}
