using Microsoft.CodeAnalysis;

using static Aetos.Tracing.Constants;

namespace Aetos.Tracing;

public partial class EventListenerGenerator
{
    internal const string GeneratedEventListenerAttributeCode =
        $$"""
          // <auto-generated/>

          namespace {{Namespace}}
          {
              [global::Microsoft.CodeAnalysis.Embedded]
              [global::System.AttributeUsage(global::System.AttributeTargets.Class)]
              [global::System.Diagnostics.Conditional("COMPILE_TIME_ONLY")]
              internal sealed class {{GeneratedEventListenerAttributeName}} : global::System.Attribute
              {
                  public {{GeneratedEventListenerAttributeName}}(
                      global::System.String eventSourceName,
                      global::System.Type eventSchema)
                  {
                      this.EventSourceName = eventSourceName;
                      this.EventSchema = eventSchema;
                  }

                  public global::System.String EventSourceName { get; }

                  public global::System.Type EventSchema { get; }
              }
          }
          """;

    public static void PostInitialize(
        IncrementalGeneratorPostInitializationContext context)
    {
        context.AddEmbeddedAttributeDefinition();

        context.AddSource(GeneratedEventListenerAttributeFileName, GeneratedEventListenerAttributeCode);
    }
}
