using System.Collections.Generic;
using System.Linq;

using Microsoft.CodeAnalysis;

using Aetos.Tracing.Models;

using static Aetos.Tracing.Constants;

namespace Aetos.Tracing;

internal static class EventListenerBaseEmitter
{
    public static void EmitEventListenerBase(
        SourceProductionContext context,
        EventSourceMethodInfoWithDiagnostics input)
    {
        if (input.SourceInfo is not { } methodInfo)
        {
            return;
        }

        var codeBuilder = new IndentedStringBuilder();

        codeBuilder.AppendLineWithIndent("// <auto-generated>");
        codeBuilder.AppendLineWithIndent();

        if (methodInfo.NamespaceSegments.Count != 0)
        {
            var namespaceName = string.Join(".", methodInfo.NamespaceSegments);
            codeBuilder.AppendLineWithIndent($"namespace {namespaceName}");
            codeBuilder.AppendLineWithIndent("{");
            codeBuilder.Indent();
        }

        foreach (var containingType in methodInfo.ContainingTypes)
        {
            codeBuilder.AppendLineWithIndent($"partial {containingType.KindKeyword} {containingType.Name}");
            codeBuilder.AppendLineWithIndent("{");
            codeBuilder.Indent();
        }

        codeBuilder.AppendLineWithIndent(
            """
            public abstract partial class ListenerBase : global::System.Diagnostics.Tracing.EventListener
            {
            """);
        codeBuilder.Indent();

        var metadata = methodInfo.Metadata;
        var eventId = metadata.EventId;
        var eventLevel = metadata.Level;
        var eventKeywords = string.Join(" | ", metadata.Keywords);

        codeBuilder.AppendLineWithIndent($"[global::{GeneratedEventAttributeFullName}({eventId}, {eventLevel}, {eventKeywords})]");
        codeBuilder.AppendWithIndent($"protected virtual void {methodInfo.MethodName}");

        var parameters = methodInfo.Parameters;
        var parametersCount = parameters.Count;

        if (parametersCount == 0)
        {
            codeBuilder.AppendWithoutIndent("()");
            codeBuilder.AppendLineWithoutIndent();
        }
        else
        {
            codeBuilder.AppendWithoutIndent("(");
            codeBuilder.AppendLineWithoutIndent();
            codeBuilder.Indent();

            var lastParameterIndex = parametersCount - 1;

            for (var i = 0; i <= lastParameterIndex; ++i)
            {
                var parameter = parameters[i];
                var delimiter = i < lastParameterIndex ? "," : ")";

                if (parameter.IsRelatedActivityIdParameter)
                {
                    continue;
                }

                codeBuilder.AppendLineWithIndent($"{parameter.FullyQualifiedTypeName} {parameter.Name}{delimiter}");
            }

            codeBuilder.Unindent();
        }

        codeBuilder.AppendLineWithIndent("{");
        codeBuilder.Indent();

        // method
        codeBuilder.Unindent();
        codeBuilder.AppendLineWithIndent("}");

        // class
        codeBuilder.Unindent();
        codeBuilder.AppendLineWithIndent(
            """
            }
            """);

        // enclosing class and namespace
        while (codeBuilder.IndentationLevel != 0)
        {
            codeBuilder.Unindent();
            codeBuilder.AppendLineWithIndent("}");
        }

        var code = codeBuilder.ToString();

        var fileNameSegment = new List<string>();

        fileNameSegment.AddRange(methodInfo.NamespaceSegments);
        fileNameSegment.AddRange(methodInfo.ContainingTypes.Select(static x => x.Name));
        fileNameSegment.Add("ListenerBase");
        fileNameSegment.Add(methodInfo.MethodName);
        fileNameSegment.Add(GeneratedFileExtension);

        var fileName = string.Join(".", fileNameSegment);

        context.AddSource(fileName, code);
    }
}
