using System.Collections.Generic;
using System.Linq;

using Aetos.Tracing.Models;

using Microsoft.CodeAnalysis;

namespace Aetos.Tracing;

internal static class EventSourceEmitter
{
    public static void EmitEventSourceMethod(
        SourceProductionContext context,
        EventSourceMethodInfoWithDiagnostics input)
    {
        foreach (var diagnostic in input.Diagnostics)
        {
            context.ReportDiagnostic(diagnostic.CreateDiagnostic());
        }

        if (input.MethodInfo is not { } methodInfo)
        {
            return;
        }

        var codeBuilder = new IndentedStringBuilder();

        codeBuilder.AppendLineWithIndent("// <auto-generated>");
        codeBuilder.AppendLineWithIndent();

        if (methodInfo.NamespaceSegments.Count != 0)
        {
            var namespaceName = string.Join(".", methodInfo.NamespaceSegments);
            codeBuilder.AppendLineWithIndent($"namespace {namespaceName}");
            codeBuilder.AppendLineWithIndent("{");
            codeBuilder.Indent();
        }

        foreach (var containingType in methodInfo.ContainingTypes)
        {
            codeBuilder.AppendLineWithIndent($"partial {containingType.KindKeyword} {containingType.Name}");
            codeBuilder.AppendLineWithIndent("{");
            codeBuilder.Indent();
        }

        var parameters = methodInfo.Parameters;
        var parametersCount = parameters.Count;

        codeBuilder.AppendWithIndent($"{methodInfo.AccessibilityKeyword} partial void {methodInfo.MethodName}");

        if (parametersCount == 0)
        {
            codeBuilder.AppendWithoutIndent("()");
            codeBuilder.AppendLineWithoutIndent();
        }
        else
        {
            codeBuilder.AppendWithoutIndent("(");
            codeBuilder.AppendLineWithoutIndent();
            codeBuilder.Indent();

            var lastParameterIndex = parametersCount - 1;
            for (var i = 0; i <= lastParameterIndex; ++i)
            {
                var parameter = parameters[i];
                var delimiter = i < lastParameterIndex ? "," : ")";

                codeBuilder.AppendLineWithIndent($"{parameter.FullyQualifiedTypeName} {parameter.Name}{delimiter}");
            }

            codeBuilder.Unindent();
        }

        codeBuilder.AppendLineWithIndent("{");
        codeBuilder.Indent();

        codeBuilder.AppendLineWithIndent(
            $$"""
              if (!this.IsEnabled(global::System.Diagnostics.Tracing.EventLevel.{{methodInfo.Metadata.Level}}, global::System.Diagnostics.Tracing.EventKeywords.None))
              {
              """);
        codeBuilder.Indent();
        codeBuilder.AppendLineWithIndent("return;");
        codeBuilder.Unindent();
        codeBuilder.AppendLineWithIndent("}");
        codeBuilder.AppendLineWithoutIndent();

        var metadata = methodInfo.Metadata;
        var eventId = metadata.EventId;

        codeBuilder.AppendLineWithIndent(
            """
            unsafe
            {
            """);
        codeBuilder.Indent();

        var byteArrayParameterCount = parameters.Count(static x => x.FullyQualifiedTypeName == "global::System.Byte[]");

        if (parametersCount == 0)
        {
            codeBuilder.AppendLineWithIndent($"this.WriteEventCore({eventId}, 0, null);");
        }
        else
        {
            codeBuilder.AppendLineWithIndent($"global::System.Diagnostics.Tracing.EventSource.EventData *data = stackalloc global::System.Diagnostics.Tracing.EventSource.EventData[{parametersCount + byteArrayParameterCount}];");
            codeBuilder.AppendLineWithoutIndent();

            for (var i = 0; i < parametersCount; ++i)
            {
                var (typeName, parameterName) = parameters[i];

                switch (typeName)
                {
                    case "global::System.Boolean":
                        codeBuilder.AppendLineWithIndent($"int __arg{i}Value = {parameterName} ? 1 : 0;");
                        WriteData(codeBuilder, i, $"__arg{i}Value", "4");
                        break;

                    case "global::System.Byte":
                    case "global::System.SByte":
                        WriteData(codeBuilder, i, parameterName, "1");
                        break;

                    case "global::System.Char":
                    case "global::System.Int16":
                    case "global::System.UInt16":
                        WriteData(codeBuilder, i, parameterName, "2");
                        break;

                    case "global::System.Int32":
                    case "global::System.UInt32":
                    case "global::System.Single":
                        WriteData(codeBuilder, i, parameterName, "4");
                        break;

                    case "global::System.Int64":
                    case "global::System.UInt64":
                    case "global::System.Double":
                        WriteData(codeBuilder, i, parameterName, "8");
                        break;

                    case "global::System.String":
                        codeBuilder.AppendLineWithIndent(
                            $$"""
                              {{parameterName}} ??= "";
                              fixed (char *__arg{{i}}Value = {{parameterName}})
                              {
                              """);
                        codeBuilder.Indent();
                        codeBuilder.AppendLineWithIndent(
                            $$"""
                              data[{{i}}].DataPointer = (global::System.IntPtr)__arg{{i}}Value;
                              data[{{i}}].Size = ({{parameterName}}.Length + 1) * 2;
                              """);
                        codeBuilder.Unindent();
                        codeBuilder.AppendLineWithIndent(
                            """
                            }
                            """);
                        codeBuilder.AppendLineWithoutIndent();
                        break;

                    case "global::System.DateTime":
                        codeBuilder.AppendLineWithIndent($"long __arg{i}Value = {parameterName}.ToFileTimeUtc();");
                        WriteData(codeBuilder, i, $"__arg{i}Value", "8");
                        break;

                    case "global::System.Guid":
                    case "global::System.Decimal":
                        WriteData(codeBuilder, i, parameterName, "16");
                        break;

                    case "global::System.IntPtr":
                        WriteData(codeBuilder, i, parameterName, "global::System.IntPtr.Size");
                        break;

                    case "global::System.Byte[]":
                        codeBuilder.AppendLineWithIndent(
                            $$"""
                              if ({{parameterName}} == null || {{parameterName}}.Length == 0)
                              {
                              """);
                        codeBuilder.Indent();
                        codeBuilder.AppendLineWithIndent(
                            $$"""
                              int blobSize = 0;
                              data[{{i}}].DataPointer = (global::System.IntPtr)(&blobSize);
                              data[{{i}}].Size = 4;
                              """);
                        codeBuilder.AppendLineWithIndent($"data[{i + 1}].DataPointer = (global::System.IntPtr)(&blobSize);");
                        codeBuilder.AppendLineWithIndent($"data[{i + 1}].Size = 0;");
                        codeBuilder.Unindent();
                        codeBuilder.AppendLineWithIndent(
                            """
                            }
                            else
                            {
                            """);
                        codeBuilder.Indent();
                        codeBuilder.AppendLineWithIndent(
                            $$"""
                              int blobSize = {{parameterName}}.Length;
                              fixed (byte *blob = &{{parameterName}}[0])
                              {
                              """);
                        codeBuilder.Indent();
                        codeBuilder.AppendLineWithIndent(
                            $$"""
                              data[{{i}}].DataPointer = (global::System.IntPtr)(&blobSize);
                              data[{{i}}].Size = 4;
                              data[{{i + 1}}].DataPointer = (global::System.IntPtr)blob;
                              data[{{i + 1}}].Size = blobSize;
                              """);
                        codeBuilder.Unindent();
                        codeBuilder.AppendLineWithIndent(
                            """
                            }
                            """);
                        codeBuilder.Unindent();
                        codeBuilder.AppendLineWithIndent(
                            """
                            }
                            """);
                        codeBuilder.AppendLineWithoutIndent();
                        ++i;
                        break;
                }
            }

            codeBuilder.AppendLineWithIndent($"this.WriteEventCore({eventId}, {parametersCount + byteArrayParameterCount}, data);");
        }

        codeBuilder.Unindent();
        codeBuilder.AppendLineWithIndent("}");

        while (codeBuilder.IndentationLevel != 0)
        {
            codeBuilder.Unindent();
            codeBuilder.AppendLineWithIndent("}");
        }

        var code = codeBuilder.ToString();

        var fileNameSegment = new List<string>();

        fileNameSegment.AddRange(methodInfo.NamespaceSegments);
        fileNameSegment.AddRange(methodInfo.ContainingTypes.Select(static x => x.Name));
        fileNameSegment.Add(methodInfo.MethodName);
        fileNameSegment.Add("g.cs");

        var fileName = string.Join(".", fileNameSegment);

        context.AddSource(fileName, code);

        static void WriteData(
            IndentedStringBuilder codeBuilder,
            int parameterIndex,
            string parameterName,
            string parameterSizeExpression)
        {
            codeBuilder.AppendLineWithIndent($"data[{parameterIndex}].DataPointer = (global::System.IntPtr)(&{parameterName});");
            codeBuilder.AppendLineWithIndent($"data[{parameterIndex}].Size = {parameterSizeExpression};");
            codeBuilder.AppendLineWithoutIndent();
        }
    }
}
