using Microsoft.CodeAnalysis;

namespace Aetos.Tracing;

public partial class TraceEventGenerator
{
    internal const string GeneratedEventSourceAttributeFileName = "Aetos.Tracing.GeneratedEventSourceAttribute.g.cs";

    internal const string GeneratedEventListenerAttributeFileName = "Aetos.Tracing.GeneratedEventListenerAttribute.g.cs";

    internal const string GeneratedEventMappingAttributeFileName = "Aetos.Tracing.GeneratedEventMappingAttribute.g.cs";

    internal const string GeneratedEventSourceAttributeCode =
        """
        // <auto-generated/>

        namespace Aetos.Tracing
        {
            [global::Microsoft.CodeAnalysis.Embedded]
            [global::System.AttributeUsage(global::System.AttributeTargets.Class)]
            [global::System.Diagnostics.Conditional("COMPILE_TIME_ONLY")]
            internal sealed class GeneratedEventSourceAttribute : global::System.Attribute
            {
            }
        }
        """;

    internal const string GeneratedEventListenerAttributeCode =
        """
        // <auto-generated/>

        namespace Aetos.Tracing
        {
            [global::Microsoft.CodeAnalysis.Embedded]
            [global::System.AttributeUsage(global::System.AttributeTargets.Class)]
            [global::System.Diagnostics.Conditional("COMPILE_TIME_ONLY")]
            internal sealed class GeneratedEventListenerAttribute : global::System.Attribute
            {
                public GeneratedEventListenerAttribute(string eventSourceName)
                {
                    this.EventSourceName = eventSourceName;
                }

                public string EventSourceName { get; }
            }
        }
        """;

    internal const string GeneratedEventMappingAttributeCode =
        """
        // <auto-generated/>

        namespace Aetos.Tracing
        {
            [global::Microsoft.CodeAnalysis.Embedded]
            [global::System.AttributeUsage(global::System.AttributeTargets.Method)]
            internal sealed class GeneratedEventMappingAttribute : global::System.Attribute
            {
                public GeneratedEventMappingAttribute(
                    int eventId,
                    global::System.Diagnostics.Tracing.EventLevel level,
                    global::System.Diagnostics.Tracing.EventKeywords keywords)
                {
                    this.EventId = eventId;
                    this.Level = level;
                    this.Keywords = keywords;
                }

                public int EventId { get; }

                public global::System.Diagnostics.Tracing.EventLevel Level { get; }

                public global::System.Diagnostics.Tracing.EventKeywords Keywords { get; }
            }
        }
        """;

    private static void PostInitialize(
        IncrementalGeneratorPostInitializationContext context)
    {
        context.AddEmbeddedAttributeDefinition();

        context.AddSource(GeneratedEventSourceAttributeFileName, GeneratedEventSourceAttributeCode);
        context.AddSource(GeneratedEventListenerAttributeFileName, GeneratedEventListenerAttributeCode);
        context.AddSource(GeneratedEventMappingAttributeFileName, GeneratedEventMappingAttributeCode);
    }
}
