using Microsoft.CodeAnalysis;

using static Aetos.Tracing.Constants;

namespace Aetos.Tracing;

public partial class TraceEventGenerator
{
    internal const string GeneratedEventSourceAttributeCode =
        $$"""
        // <auto-generated/>

        namespace {{Namespace}}
        {
            [global::Microsoft.CodeAnalysis.Embedded]
            [global::System.AttributeUsage(global::System.AttributeTargets.Class)]
            [global::System.Diagnostics.Conditional("COMPILE_TIME_ONLY")]
            internal sealed class {{GeneratedEventSourceAttributeName}} : global::System.Attribute
            {
            }
        }
        """;

    internal const string GeneratedEventListenerAttributeCode =
        $$"""
        // <auto-generated/>

        namespace {{Namespace}}
        {
            [global::Microsoft.CodeAnalysis.Embedded]
            [global::System.AttributeUsage(global::System.AttributeTargets.Class)]
            [global::System.Diagnostics.Conditional("COMPILE_TIME_ONLY")]
            internal sealed class {{GeneratedEventListenerAttributeName}} : global::System.Attribute
            {
                public {{GeneratedEventListenerAttributeName}}(string eventSourceName)
                {
                    this.EventSourceName = eventSourceName;
                }

                public string EventSourceName { get; }
            }
        }
        """;

    internal const string GeneratedEventAttributeCode =
        $$"""
        // <auto-generated/>

        namespace {{Namespace}}
        {
            [global::Microsoft.CodeAnalysis.Embedded]
            [global::System.AttributeUsage(global::System.AttributeTargets.Method)]
            internal sealed class {{GeneratedEventAttributeName}} : global::System.Attribute
            {
                public {{GeneratedEventAttributeName}}(
                    int eventId,
                    global::System.Diagnostics.Tracing.EventLevel level,
                    global::System.Diagnostics.Tracing.EventKeywords keywords)
                {
                    this.EventId = eventId;
                    this.Level = level;
                    this.Keywords = keywords;
                }

                public int EventId { get; }

                public global::System.Diagnostics.Tracing.EventLevel Level { get; }

                public global::System.Diagnostics.Tracing.EventKeywords Keywords { get; }
            }
        }
        """;

    private static void PostInitialize(
        IncrementalGeneratorPostInitializationContext context)
    {
        context.AddEmbeddedAttributeDefinition();

        context.AddSource(GeneratedEventSourceAttributeFileName, GeneratedEventSourceAttributeCode);
        context.AddSource(GeneratedEventListenerAttributeFileName, GeneratedEventListenerAttributeCode);
        context.AddSource(GeneratedEventAttributeFileName, GeneratedEventAttributeCode);
    }
}
