using Microsoft.CodeAnalysis;

namespace Aetos.Tracing;

public partial class TraceEventGenerator
{
    internal const string GeneratedEventSourceAttributeFileName = "GeneratedEventSourceAttribute.g.cs";

    internal const string GeneratedEventListenerAttributeFileName = "GeneratedEventListenerAttribute.g.cs";

    internal const string GeneratedEventSourceAttributeCode =
        """
        // <auto-generated/>

        namespace Aetos.Tracing
        {
            [global::Microsoft.CodeAnalysis.Embedded]
            [global::System.AttributeUsage(global::System.AttributeTargets.Class)]
            [global::System.Diagnostics.Conditional("COMPILE_TIME_ONLY")]
            internal sealed class GeneratedEventSourceAttribute : global::System.Attribute
            {
            }
        }
        """;

    internal const string GeneratedEventListenerAttributeCode =
        """
        // <auto-generated/>

        namespace Aetos.Tracing
        {
            [global::Microsoft.CodeAnalysis.Embedded]
            [global::System.AttributeUsage(global::System.AttributeTargets.Class)]
            [global::System.Diagnostics.Conditional("COMPILE_TIME_ONLY")]
            internal sealed class GeneratedEventListenerAttribute : global::System.Attribute
            {
                public GeneratedEventListenerAttribute(string eventSourceName)
                {
                    this.EventSourceName = eventSourceName;
                }

                public string EventSourceName { get; }
            }
        }
        """;


    private static void PostInitialize(
        IncrementalGeneratorPostInitializationContext context)
    {
        context.AddEmbeddedAttributeDefinition();

        context.AddSource(GeneratedEventSourceAttributeFileName, GeneratedEventSourceAttributeCode);
        context.AddSource(GeneratedEventListenerAttributeFileName, GeneratedEventListenerAttributeCode);
    }
}
