
using System.Data;
using System.Text;
using System.Threading;

using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace Aetos.Tracing;

public partial class TraceEventGenerator
{
    private static EventSourceInfo ParseEventSourceClass(
        SemanticModel semanticModel,
        ClassDeclarationSyntax node,
        INamedTypeSymbol symbol,
        CancellationToken cancellationToken)
    {
        var parser = new EventSourceParser(semanticModel);

        return parser.ParseType(
            node,
            symbol,
            cancellationToken);
    }

    private static void EmitEventSourceClass(
        SourceProductionContext context,
        EventSourceInfo source)
    {
        foreach (var diagnostic in source.Diagnostics)
        {
            context.ReportDiagnostic(diagnostic.CreateDiagnostic());
        }

        if (source.ClassInfo is not {} classInfo)
        {
            return;
        }

        var codeBuilder = new StringBuilder();

        codeBuilder.AppendLine("// <auto-generated/>");
        codeBuilder.AppendLine();

        if (classInfo.Namespace is not null)
        {
        }

        var code = codeBuilder.ToString();

        var fileName = classInfo.Namespace is null
            ? $"{classInfo.TypeName}.g.cs"
            : $"{classInfo.Namespace}.{classInfo.TypeName}.g.cs";

        context.AddSource(fileName, code);
    }
}
