// <auto-generated/>

using System;
using System.Collections.Generic;
using System.Diagnostics.CodeAnalysis;
using System.Diagnostics.Tracing;
using System.Runtime.CompilerServices;
using System.Text;

namespace EventProducerProject;

partial class SampleEventSource
{
    [UnconditionalSuppressMessage("ReflectionAnalysis", "IL2026:RequiresUnreferencedCode", Justification = "foobar")]
    public partial void Foo(int i1, int i2)
    {
        if (!this.IsEnabled(EventLevel.Informational, Keywords.A))
        {
            return;
        }

        unsafe
        {
            EventData* data = stackalloc EventData[2];

            data[0].DataPointer = (IntPtr)(&i1);
            data[0].Size = 4;
            data[1].DataPointer = (IntPtr)(&i2);
            data[1].Size = 4;

            this.WriteEventWithRelatedActivityIdCore(1, null, 2, data);
        }
    }

    [UnconditionalSuppressMessage("ReflectionAnalysis", "IL2026:RequiresUnreferencedCode", Justification = "foobar")]
    public partial void Bar(Guid relatedActivityId, string s, int i, byte[] b)
    {
        if (!this.IsEnabled(EventLevel.Verbose, Keywords.B))
        {
            return;
        }

        unsafe
        {
            EventData* data = stackalloc EventData[4];

            s ??= "";

            // パラメーターごとにネストを深くしたくないので、すべての string / byte をまとめてピン留めする
            fixed (char* ps = s)
            fixed (byte* pb = b)
            {
                data[0].DataPointer = (IntPtr)ps;
                data[0].Size = (s.Length + 1) * 2;

                data[1].DataPointer = (IntPtr)(&i);
                data[1].Size = 4;

                int blobSize = 0;

                data[2].DataPointer = (IntPtr)(&blobSize);
                data[2].Size = 4;

                if (b == null || b.Length == 0)
                {
                    data[3].DataPointer = (IntPtr)(&blobSize);
                    data[3].Size = 0;
                }
                else
                {
                    blobSize = b.Length;
                    data[3].DataPointer = (IntPtr)pb;
                    data[3].Size = blobSize;
                }

                this.WriteEventWithRelatedActivityIdCore(2, &relatedActivityId, 4, data);
            }
        }
    }

    [UnconditionalSuppressMessage("ReflectionAnalysis", "IL2026:RequiresUnreferencedCode", Justification = "foobar")]
    public partial void Baz()
    {
        if (!this.IsEnabled(EventLevel.Warning, Keywords.C))
        {
            return;
        }

        unsafe
        {
            this.WriteEventWithRelatedActivityIdCore(3, null, 0, null);
        }
    }
}
